### ISSUE TITLE
How does the summary linking works?

### ISSUE THREAD

**Issue by bekihm** [apiman/apiman-docs-user-guide#2]
@EricWittmann I try to create a link between the SUMMARY.adoc and policies.adoc for the Caching Resources Policy like it is done for other policies.
But I don't figure out how the existing links work especially on your webpage later on.

How matches this link in SUMMARY.adoc
`.. link:user-guide/gateway/policies.adoc#_basic_authentication_policy[BASIC Auth]`
to this paragraph in policies.adoc:
`== BASIC Authentication Policy
[[policy-basic-auth]]`

**Comment by EricWittmann** [comment]
I believe the anchor is derived from the header.  So in the example you provided, the text **BASIC Authentication Policy** becomes the anchor `_basic_authentication_policy` by making everything lowercase and swapping spaces for `_`.

That said, the documentation is all in Gitbook now, which @msavy did all the work on.  So we should get his take on this stuff.

**Comment by msavy** [comment]
Obsolete. Closing. Thanks, everyone.
