### ISSUE TITLE
User Guide - URL seems pinned to #_jwt_policy when clicking on policies

### ISSUE THREAD

**Issue by EricWittmann** [apiman/apiman-docs-user-guide#3]
When clicking on any of the policies in section 2.2, the browser will navigate to the proper section, but once the scrolling is done the URL anchor seems to switch from whatever was clicked on (e.g. `#_ip_blacklist_policy`) to `#_jwt_policy` which causes the wrong policy to be highlighted in the list (on the left).  And also reloading the page will scroll to the wrong policy.

**Comment by EricWittmann** [comment]
Also the JWT policy **cannot** be selected - it simply won't scroll to that one.  I presume because it thinks it's already there.

**Comment by bekihm** [comment]
I am currently sorting the document. I did not find the JWT policy in the policy.adoc file. I think this is the reason why the link does not work.

**Comment by EricWittmann** [comment]
I'm honestly not sure how the gitbook stuff works - and haven't had time to dig into it.  Hoping @msavy sees this and can give us a quick primer. :)

**Comment by msavy** [comment]
Will hopefully have time to look this weekend. Very busy at work right now
finishing up some stuff

**Comment by msavy** [comment]
Obsolete. Closing. Thanks, everyone.
